FROM gcc:latest

COPY . /home/irbis/Netology/homework/Multithread_and_asynch/hw_7.5

WORKDIR /home/irbis/Netology/homework/Multithread_and_asynch/hw_7.5

RUN g++ -o hw_07_05_2 hw_07_05_2.cpp

CMD ["./hw_07_05_2"]

LABEL Name=hw7_2 Version=0.0.1
